version: '3.7'

services:
  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    volumes:
        - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - '3008:8080'
    environment:
      - URL=swagger.json
    depends_on:
      - api

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      args:
        INSTALL_PYTHON_VERSION: 3.8.2
    volumes:
      - ./services/api:/code
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - VERSION=${VERSION}
      - APP_CONFIG=app.main.config.DevelopmentConfig
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/api_test
      # In minutes
      - ACCESS_TOKEN_EXPIRES=5
      - REFRESH_TOKEN_EXPIRES=60
    depends_on:
      - db

  db:
    build:
      context: ./services/api/dev.db
      dockerfile: Dockerfile
      args:
        INSTALL_POSTGRES_VERSION: 11.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
      args:
        INSTALL_NGINX_VERSION: 1.15.9
    restart: always
    ports:
      - 80:80
    depends_on:
      - api

volumes:
    data:
